// Mock GHC (Copilot) UPSTREAM for the Responses buffered-merge Codex real-consumer oracle
// (spec 2026-07-14-responses-buffered-block-merge §8.2 / plan Task 5.6 — NON-BLOCKING, manual).
//
// TOPOLOGY:  real Codex CLI (`codex exec`)  ──▶  copilot-api PROXY (buffered ON)  ──ghc_api_base_url──▶  THIS mock.
//   The mock sits UPSTREAM of the proxy; what's under test is whether a REAL Codex consumer tolerates the
//   proxy's drop-delta MERGED forwarded wire the same as the unmerged VERBATIM wire.
//
// TWO ARMS (MOCK_ARM env):
//   - armVerbatim: a function_call generation WITH the per-`.delta` frames (the raw upstream shape).
//   - armMerged:   the SAME generation with every `.delta` frame REMOVED (the drop-delta shape a client
//                  would receive through the proxy). Both carry an IDENTICAL `response.completed` output,
//                  so the two arms are SEMANTICALLY EQUIVALENT — only the wire frame count differs.
//   Running Codex against each arm answers: does dropping the deltas change what Codex reconstructs?
//
// TRANSPORT: node:http2 secure server (HTTPS/h2), NOT Bun.serve HTTP/1.1 — same reason as the sibling
// exp/responses-keepalive-idle-oracle/mock-upstream.ts: the proxy's upstream fetch routes `https://`
// through node:http2 (its PRODUCTION path) and `http://` through undici (which hangs under Bun on SSE).
// Self-signed localhost cert generated by run-proxy-arm.sh if absent.

import http2 from "node:http2"
import { readFileSync } from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

const HERE = path.dirname(fileURLToPath(import.meta.url))
const PORT = Number(process.env.MOCK_UPSTREAM_PORT ?? 8788)
const CERT_PATH = process.env.MOCK_CERT ?? path.join(HERE, "mock-cert.pem")
const KEY_PATH = process.env.MOCK_KEY ?? path.join(HERE, "mock-key.pem")
const MODEL_ID = process.env.MOCK_MODEL_ID ?? "gpt-5.5"
const ARM = process.env.MOCK_ARM ?? "verbatim" // "verbatim" | "merged"

/** Minimal Copilot model catalogue — the proxy builds its model index from GET /models and only needs
 *  the arm's model routable to /responses. Self-contained (no external refs/AVAILABLE_MODELS.json). */
const MODELS_BODY = JSON.stringify({
  object: "list",
  data: [
    {
      id: MODEL_ID,
      object: "model",
      vendor: "OpenAI",
      capabilities: { family: MODEL_ID, type: "chat", supports: { streaming: true, tool_calls: true } },
      supported_endpoints: ["/responses", "/chat/completions"],
      model_picker_enabled: true,
    },
  ],
})

const t0 = performance.now()
const rel = () => `+${((performance.now() - t0) / 1000).toFixed(2)}s`
const log = (...a: Array<unknown>) => console.error(`[mock-upstream ${rel()}]`, ...a)

const enc = new TextEncoder()
const sse = (event: string, data: unknown): Uint8Array => enc.encode(`event: ${event}\ndata: ${JSON.stringify(data)}\n\n`)

const RESPONSE_ID = "resp_buffered_merge_oracle"
const FC_OPEN = { id: "fc_1", type: "function_call", call_id: "call_1", name: "get_weather", arguments: "", status: "in_progress" }
const FC_DONE = { id: "fc_1", type: "function_call", call_id: "call_1", name: "get_weather", arguments: '{"city":"Tokyo"}', status: "completed" }

const created = (): Uint8Array => sse("response.created", { type: "response.created", sequence_number: 0, response: { id: RESPONSE_ID, object: "response", status: "in_progress", model: MODEL_ID, output: [] } })
const completed = (seq: number): Uint8Array =>
  sse("response.completed", { type: "response.completed", sequence_number: seq, response: { id: RESPONSE_ID, object: "response", status: "completed", model: MODEL_ID, output: [FC_DONE], usage: { input_tokens: 5, output_tokens: 3, total_tokens: 8 } } })

/** VERBATIM: created → added → args.delta×2 → args.done → output_item.done → completed. */
function armVerbatimFrames(): Array<Uint8Array> {
  return [
    created(),
    sse("response.output_item.added", { type: "response.output_item.added", sequence_number: 1, output_index: 0, item: FC_OPEN }),
    sse("response.function_call_arguments.delta", { type: "response.function_call_arguments.delta", sequence_number: 2, output_index: 0, item_id: "fc_1", delta: '{"city":' }),
    sse("response.function_call_arguments.delta", { type: "response.function_call_arguments.delta", sequence_number: 3, output_index: 0, item_id: "fc_1", delta: '"Tokyo"}' }),
    sse("response.function_call_arguments.done", { type: "response.function_call_arguments.done", sequence_number: 4, output_index: 0, item_id: "fc_1", arguments: '{"city":"Tokyo"}' }),
    sse("response.output_item.done", { type: "response.output_item.done", sequence_number: 5, output_index: 0, item: FC_DONE }),
    completed(6),
  ]
}

/** MERGED (drop-delta): the SAME generation with the two `.delta` frames removed. */
function armMergedFrames(): Array<Uint8Array> {
  return [
    created(),
    sse("response.output_item.added", { type: "response.output_item.added", sequence_number: 1, output_index: 0, item: FC_OPEN }),
    sse("response.function_call_arguments.done", { type: "response.function_call_arguments.done", sequence_number: 4, output_index: 0, item_id: "fc_1", arguments: '{"city":"Tokyo"}' }),
    sse("response.output_item.done", { type: "response.output_item.done", sequence_number: 5, output_index: 0, item: FC_DONE }),
    completed(6),
  ]
}

function readBody(stream: http2.ServerHttp2Stream): Promise<Buffer> {
  return new Promise((resolve) => {
    const chunks: Array<Buffer> = []
    stream.on("data", (c: Buffer) => chunks.push(c))
    stream.on("end", () => resolve(Buffer.concat(chunks)))
    stream.on("error", () => resolve(Buffer.concat(chunks)))
  })
}

const server = http2.createSecureServer({ key: readFileSync(KEY_PATH), cert: readFileSync(CERT_PATH), ALPNProtocols: ["h2"] })
server.on("sessionError", (err) => log(`(sessionError absorbed) ${String(err)}`))
server.on("clientError", (err) => log(`(clientError absorbed) ${String(err)}`))

server.on("stream", (stream, headers) => {
  stream.on("error", (err) => log(`(stream error absorbed) ${String(err)}`))
  const method = String(headers[":method"] ?? "GET")
  const pathname = String(headers[":path"] ?? "/").split("?")[0]

  void (async (): Promise<void> => {
    if (method === "GET" && pathname.endsWith("/models")) {
      stream.respond({ ":status": 200, "content-type": "application/json", etag: `"mock-upstream-${PORT}"` })
      stream.end(MODELS_BODY)
      return
    }
    if (!pathname.endsWith("/responses")) {
      await readBody(stream)
      stream.respond({ ":status": 200, "content-type": "application/json" })
      stream.end(JSON.stringify({ ok: true, note: "mock GHC upstream" }))
      return
    }
    await readBody(stream)
    const frames = ARM === "merged" ? armMergedFrames() : armVerbatimFrames()
    log(`POST ${pathname} arm=${ARM} → ${frames.length} SSE frames`)
    stream.respond({ ":status": 200, "content-type": "text/event-stream" })
    for (const f of frames) stream.write(Buffer.from(f))
    stream.end()
  })()
})

server.listen(PORT, () => log(`listening on https://localhost:${PORT} (arm=${ARM}, model=${MODEL_ID})`))
