[install]
registry = { url = "https://registry.npmjs.org", token = "$NPM_TOKEN" }

[publish]
registry = "https://registry.npmjs.org"
token = "$NPM_TOKEN"

[test]
root = "./tests"
coverage = true
coverageReporter = ["text", "lcov"]
coverageDir = "coverage"
